baseurl      = "toddtee.sh"
title        = "Todd Turner"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Engineer, Developer, Infrastructure"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[[params.social]]
  name = "github"
  url = "https://github.com/toddtee"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/toddtee"

[[params.social]]
  name = "email"
  url = "hi@toddtee.sh"

[[params.social]]
  name = "keybase"
  url = "https://keybase.io/toddtee"

[[params.social]]
  name = "gpg"
  url = "A3575FCC1FFA92728CAFA00008AFCE1FF34F3675"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Todd Turner"
    subtitle = "For Sure"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "fumbling in the dark"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "contact"
    name       = "Say Hi"
    url        = "/contact"
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/resume"

