name: release-development
on:
  push:
    branches:
      - development
  pull_request:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

  get-hugo:
    runs-on: ubuntu-latest
    steps:
      - name: install-hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

  build:
    needs: [checkout-repo, get-hugo]
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: hugo --minify

  release-development:
    needs: [checkout-repo, get-hugo, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: read
    steps:
      - name: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::621936952358:role/infrastructure-ci-Role-1EBR5QIBIRAR7
          aws-region: ap-southeast-2
      - name: test
        run: |
          aws s3 ls
